---
- name: Create VDS and Swing management VMK onto it
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  vars:
    vcenter_hostname: "vcenter.home.soksy.org"
    datacenter: "myDC"
    storage_mtu: 1700
    esxilist:
      - esxi_hostname: "esxi8-00.vmware.soksy.org"
      - esxi_hostname: "esxi8-01.vmware.soksy.org"
      - esxi_hostname: "esxi8-02.vmware.soksy.org"
      # - esxi_hostname: "esxi8-10.vmware.soksy.org"
      # - esxi_hostname: "esxi8-11.vmware.soksy.org"
      # - esxi_hostname: "esxi8-12.vmware.soksy.org"

  tasks:
    - name: Get creds from vault
      set_fact:
        vcenter_username: "{{ lookup('hashi_vault', 'secret=secret/data/vmware:vcenter_username') }}"
        vcenter_password: "{{ lookup('hashi_vault', 'secret=secret/data/vmware:vcenter_password') }}"
        esxi_username: "{{ lookup('hashi_vault', 'secret=secret/data/vmware:esxi_username') }}"
        esxi_password: "{{ lookup('hashi_vault', 'secret=secret/data/vmware:esxi_password') }}"

    - name: Create dvSwitch
      community.vmware.vmware_dvswitch:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter: '{{ datacenter }}'
        validate_certs: no
        switch: dvSwitchA
        version: 8.0.0
        mtu: '{{ storage_mtu }}'
        uplink_quantity: 2
        discovery_protocol: lldp
        discovery_operation: both
        network_policy:
          promiscuous: yes
          mac_changes: no
          forged_transmits: no
        
        state: present


    - name: Create management portgroup
      community.vmware.vmware_dvs_portgroup:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        portgroup_name: PG-Management
        switch_name: dvSwitchA
        vlan_id: 2
        num_ports: 120
        port_binding: static
        teaming_policy:
          active_uplinks: "Uplink 1"
          standby_uplinks: "Uplink 2"
          load_balance_policy: failover_explicit
        state: present

    - name: Add Host to dVS
      community.vmware.vmware_dvs_host:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        esxi_hostname: '{{ item.esxi_hostname }}'
        switch_name: dvSwitchA
        vmnics:
          - vmnic1
        state: present
      loop: "{{ esxilist }}"

    - name: Migrate Management vmk
      community.vmware.vmware_migrate_vmk:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        esxi_hostname: '{{ item.esxi_hostname }}'
        device: vmk0
        current_switch_name: vSwitch0
        current_portgroup_name: "Management Network"
        migrate_switch_name: dvSwitchA
        migrate_portgroup_name: PG-Management
      loop: "{{ esxilist }}"

    - name: Delete a VMware vSwitch in a specific host system
      community.vmware.vmware_vswitch:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        esxi_hostname: '{{ item.esxi_hostname }}'
        switch_name: vSwitch0
        state: absent
      loop: "{{ esxilist }}"

    - name: Add Host to dVS
      community.vmware.vmware_dvs_host:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        esxi_hostname: '{{ item.esxi_hostname }}'
        switch_name: dvSwitchA
        vmnics:
          - vmnic0
          - vmnic1
        state: present
      loop: "{{ esxilist }}"
