---
- name:  Add vMotion service to vmk0
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  vars:
    storage_mtu: 1700

  tasks: 
    - name: Get creds and nestedHosts info
      set_fact:
        vcenter_username: "{{ lookup('hashi_vault', 'secret=secret/data/vmware:vcenter_username') }}"
        vcenter_password: "{{ lookup('hashi_vault', 'secret=secret/data/vmware:vcenter_password') }}"
        esxi_username: "{{ lookup('hashi_vault', 'secret=secret/data/vmware:esxi_username') }}"
        esxi_password: "{{ lookup('hashi_vault', 'secret=secret/data/vmware:esxi_password') }}"
        nestedESXiHosts: "{{ lookup('env', 'nestedESXiJSONEncoded') | from_json }}"

    -  name: Add vMotion Service to vmk0
       community.vmware.vmware_vmkernel:
         hostname: "{{ vcenterHost }}"
         username: "{{ vcenter_username }}"
         password: "{{ vcenter_password }}"
         esxi_hostname: '{{ item.value.fqdn }}'
         dvswitch_name: "{{ vdsName }}"
         portgroup_name: PG-Management
         device: vmk0
         network:
           type: 'static'
           ip_address: "{{ item.value['operating-ip'] }}"
           subnet_mask: 255.255.255.0
         enable_mgmt: True
         enable_vmotion: True
         validate_certs: no
       loop: "{{ nestedESXiHosts | dict2items }}"

