---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - myNSXTvars.yml
  tasks:
    - name: Get creds from vault
      set_fact:
        nsxMgrUsername: "{{ lookup('hashi_vault','secret=secret/data/vmware:nsx_username') }}"
        nsxMgrPassword: "{{ lookup('hashi_vault','secret=secret/data/vmware:nsx_password') }}"  

    - name: Create transport zones
      vmware.ansible_for_nsxt.nsxt_transport_zones:
        hostname: "{{ nsxMgrHostname }}"
        username: "{{ nsxMgrUsername }}"
        password: "{{ nsxMgrPassword }}"
        validate_certs: "{{ validateCerts }}"
        resource_type: "PolicyTransportZone"
        display_name: "{{ item.displayName }}"
        description: "{{ item.description }}"
        transport_type: "{{ item.tzType }}"
        is_default: "{{ item.SetAsDefault}}"
        uplink_teaming_policy_names: "{{ item.named_teamings | default(omit) }}"
        state: "{{ state }}"
      with_items:
        - "{{ transportZones }}"
