---
- hosts: 127.0.0.1
  connection: local
  name: createUplinkProfiles.yaml
  vars_files:
    - myNSXTvars.yml

  tasks:
    - name: Get creds from vault
      set_fact:
        nsxMgrUsername: "{{ lookup('hashi_vault','secret=secret/data/vmware:nsx_username') }}"
        nsxMgrPassword: "{{ lookup('hashi_vault','secret=secret/data/vmware:nsx_password') }}"

    - name: Create uplink profiles
      vmware.ansible_for_nsxt.nsxt_uplink_profiles:
        hostname: "{{ nsxMgrHostname }}"
        username: "{{ nsxMgrUsername }}"
        password: "{{ nsxMgrPassword }}"
        validate_certs: "{{ validateCerts }}"
        resource_type: "UplinkHostSwitchProfile"
        display_name: "{{ item.display_name }}"
        description: "{{ item.description }}"
        transport_vlan: "{{ item.transport_vlan }}"
        mtu: "{{ item.mtu | default(omit) }}"                              # MTU, but omit if it does not exist - Needed to support VDS v7.0
        teaming: "{{ item.teaming }}"                                      # Default NIC Teaming
        named_teamings: "{{ item.named_teamings | default(omit) }}"        # Named Teaming Policy, but omit if it does not exist
        state: "present"
      with_items: "{{ uplinkProfiles }}"
