---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - myNSXTvars.yml

  tasks:    
    - name: Get creds from vault
      set_fact:
        nsxMgrUsername: "{{ lookup('hashi_vault','secret=secret/data/vmware:nsx_username') }}"
        nsxMgrPassword: "{{ lookup('hashi_vault','secret=secret/data/vmware:nsx_password') }}"
        nsxEdgeCLIPassword: "{{ lookup('hashi_vault','secret=secret/data/vmware:edge_cli_password') }}"
        nsxEdgeRootPassword: "{{ lookup('hashi_vault','secret=secret/data/vmware:edge_root_password') }}"
        nsxEdgeAuditUsername: "{{ lookup('hashi_vault','secret=secret/data/vmware:edge_audit_username') }}"
        nsxEdgeAuditPassword: "{{ lookup('hashi_vault','secret=secret/data/vmware:edge_audit_password') }}"
        vCenterUsername: "{{ lookup('hashi_vault','secret=secret/data/vmware:vcenter_username') }}"
        vCenterPassword: "{{ lookup('hashi_vault','secret=secret/data/vmware:vcenter_password') }}"  

    - name: Deploy and configure Edge Transport Nodes
      vmware.ansible_for_nsxt.nsxt_transport_nodes:
        hostname: "{{ nsxMgrHostname }}"
        username: "{{ nsxMgrUsername }}"
        password: "{{ nsxMgrPassword }}"
        validate_certs: "{{ validateCerts }}"
        display_name: "{{ item.Name }}"
        description: "{{ item.Description }}"
        host_switch_spec:
          resource_type: StandardHostSwitchSpec
          host_switches:
            - host_switch_profiles:
              - name: "Edge-Uplink-Profile"
                type: UplinkHostSwitchProfile
              host_switch_name: "{{ EdgeTransportNodes.HostSwitch.Name }}"
              host_switch_mode: "{{ EdgeTransportNodes.HostSwitch.Mode }}"
              pnics: "{{ EdgeTransportNodes.PNICS }}"
              ip_assignment_spec:
                resource_type: "{{ EdgeTransportNodes.IPPool.Type }}"
                ip_pool_name: "{{ EdgeTransportNodes.IPPool.Name }}"
              transport_zone_endpoints:
                - transport_zone_name: "{{ EdgeTransportNodes.TransportZones[0] }}"
                - transport_zone_name: "{{ EdgeTransportNodes.TransportZones[1] }}"
              
        node_deployment_info:
          resource_type: "EdgeNode"
          display_name: "{{ item.VMName }}"
          deployment_type: "VIRTUAL_MACHINE"
          deployment_config:
            form_factor: "{{ EdgeTransportNodes.Deployment.FormFactor | upper }}"
            node_user_settings:
              cli_password: "{{ nsxEdgeCLIPassword }}"
              root_password: "{{ nsxEdgeRootPassword }}"
              audit_username: "{{ nsxEdgeAuditUsername }}"
              audit_password: "{{ nsxEdgeAuditPassword }}"
            vm_deployment_config:
              management_port_subnets:
                - ip_addresses:
                    - "{{ item.ManagementIPAddress }}"
                  prefix_length: "{{ EdgeTransportNodes.Deployment.ManagementIPPrefix }}"
              default_gateway_addresses: 
                      - "{{ EdgeTransportNodes.Deployment.Gateway }}"
              placement_type: VsphereDeploymentConfig
              vc_name: "vcenter"
              vc_username: "{{ vCenterUsername }}"
              vc_password: "{{ vCenterPassword }}"
              data_networks: "{{ EdgeTransportNodes.Deployment.DataPortGroups }}"
              management_network: "{{ EdgeTransportNodes.Deployment.ManagementPortGroup }}"
              compute: "myClusterA"
              host: "{{ item.Hostname }}"
              storage:  "{{ item.Datastore }}"
              reservation_info:
                cpu_reservation:
                  reservation_in_mhz: "{{ EdgeTransportNodes.Deployment.Reservations.CPU.Megahertz }}"
                  reservation_in_shares: "{{ EdgeTransportNodes.Deployment.Reservations.CPU.Shares }}"
                memory_reservation:
                  reservation_percentage: "{{ EdgeTransportNodes.Deployment.Reservations.Memory.Percentage }}"
          node_settings:
            hostname: "{{ item.FQDN }}"
            allow_ssh_root_login: "{{ EdgeTransportNodes.Deployment.AllowRootSSH }}"
            enable_ssh: "{{ EdgeTransportNodes.Deployment.EnableSSH }}"
            search_domains:
              - "home.soksy.org"
              - "vmware.soksy.org"
            dns_servers:
              - "192.168.2.6"
            ntp_servers:
              - "192.168.2.6"
        state: present
      loop: "{{ EdgeNodes }}"
